---
name: Render the paper
run-name: Render paper
on:
  push:
    paths:
      - "**/paper.tex"
  workflow_dispatch:
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build
        run: "nix-build --arg sha \\\"${{ github.sha }}\\\" paper --out-link paper-out"
      - name: copy artefact
        run: "cp paper-out/*.pdf ." # GitHub fails to handle symlinks
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: hauser-hausch-research-paper-${{ github.sha }}.pdf
          path: hauser-hausch-research-paper-${{ github.sha }}.pdf
