---
name: Extract ISO
on:
  check_suite:
    types: [completed]
  workflow_dispatch:
jobs:
  extract-light-iso:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build
        run: "nix build .#iso-light"
      - name: copy artefact
        run: "cp result/iso/nixos.iso vm-light.iso" # GitHub fails to handle symlinks
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: vm-light.iso
          path: vm-light.iso
  extract-iso:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build
        run: "nix build .#iso"
      - name: copy artefact
        run: "cp result/iso/nixos.iso vm.iso" # GitHub fails to handle symlinks
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: vm.iso
          path: vm.iso
